language: node_js
node_js:
  - "10"
install: yarn --frozen-lockfile
cache:
  yarn: true
  directories:
    - 'node_modules'
    - '.cache'
before_script:
  - yarn build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: ./dist/
  on:
    branch: master